/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferenceRouteImport } from './routes/preference'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedMypageRouteImport } from './routes/_authenticated/mypage'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated/main'
import { Route as AuthenticatedCostRouteImport } from './routes/_authenticated/cost'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthV1RouteImport } from './routes/_auth.v1'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedCostIndexRouteImport } from './routes/_authenticated/cost.index'
import { Route as AuthenticatedBookmarksIndexRouteImport } from './routes/_authenticated/bookmarks.index'
import { Route as AuthenticatedCostCountryIdRouteImport } from './routes/_authenticated/cost.$countryId'
import { Route as AuthenticatedBookmarksIdRouteImport } from './routes/_authenticated/bookmarks.$id'

const PreferenceRoute = PreferenceRouteImport.update({
  id: '/preference',
  path: '/preference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMypageRoute = AuthenticatedMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostRoute = AuthenticatedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthV1Route = AuthV1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCostIndexRoute = AuthenticatedCostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCostRoute,
} as any)
const AuthenticatedBookmarksIndexRoute =
  AuthenticatedBookmarksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBookmarksRoute,
  } as any)
const AuthenticatedCostCountryIdRoute =
  AuthenticatedCostCountryIdRouteImport.update({
    id: '/$countryId',
    path: '/$countryId',
    getParentRoute: () => AuthenticatedCostRoute,
  } as any)
const AuthenticatedBookmarksIdRoute =
  AuthenticatedBookmarksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBookmarksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/preference': typeof PreferenceRoute
  '/login': typeof AuthLoginRoute
  '/v1': typeof AuthV1Route
  '/bookmarks': typeof AuthenticatedBookmarksRouteWithChildren
  '/cost': typeof AuthenticatedCostRouteWithChildren
  '/main': typeof AuthenticatedMainRoute
  '/mypage': typeof AuthenticatedMypageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/cost/$countryId': typeof AuthenticatedCostCountryIdRoute
  '/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
  '/cost/': typeof AuthenticatedCostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/preference': typeof PreferenceRoute
  '/login': typeof AuthLoginRoute
  '/v1': typeof AuthV1Route
  '/main': typeof AuthenticatedMainRoute
  '/mypage': typeof AuthenticatedMypageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/cost/$countryId': typeof AuthenticatedCostCountryIdRoute
  '/bookmarks': typeof AuthenticatedBookmarksIndexRoute
  '/cost': typeof AuthenticatedCostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/preference': typeof PreferenceRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/v1': typeof AuthV1Route
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRouteWithChildren
  '/_authenticated/cost': typeof AuthenticatedCostRouteWithChildren
  '/_authenticated/main': typeof AuthenticatedMainRoute
  '/_authenticated/mypage': typeof AuthenticatedMypageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/_authenticated/bookmarks/$id': typeof AuthenticatedBookmarksIdRoute
  '/_authenticated/cost/$countryId': typeof AuthenticatedCostCountryIdRoute
  '/_authenticated/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
  '/_authenticated/cost/': typeof AuthenticatedCostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preference'
    | '/login'
    | '/v1'
    | '/bookmarks'
    | '/cost'
    | '/main'
    | '/mypage'
    | '/auth/callback'
    | '/bookmarks/$id'
    | '/cost/$countryId'
    | '/bookmarks/'
    | '/cost/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preference'
    | '/login'
    | '/v1'
    | '/main'
    | '/mypage'
    | '/auth/callback'
    | '/bookmarks/$id'
    | '/cost/$countryId'
    | '/bookmarks'
    | '/cost'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/preference'
    | '/_auth/login'
    | '/_auth/v1'
    | '/_authenticated/bookmarks'
    | '/_authenticated/cost'
    | '/_authenticated/main'
    | '/_authenticated/mypage'
    | '/auth/callback'
    | '/_auth/'
    | '/_authenticated/bookmarks/$id'
    | '/_authenticated/cost/$countryId'
    | '/_authenticated/bookmarks/'
    | '/_authenticated/cost/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PreferenceRoute: typeof PreferenceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preference': {
      id: '/preference'
      path: '/preference'
      fullPath: '/preference'
      preLoaderRoute: typeof PreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mypage': {
      id: '/_authenticated/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof AuthenticatedMypageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/main': {
      id: '/_authenticated/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cost': {
      id: '/_authenticated/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthenticatedCostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/v1': {
      id: '/_auth/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof AuthV1RouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/cost/': {
      id: '/_authenticated/cost/'
      path: '/'
      fullPath: '/cost/'
      preLoaderRoute: typeof AuthenticatedCostIndexRouteImport
      parentRoute: typeof AuthenticatedCostRoute
    }
    '/_authenticated/bookmarks/': {
      id: '/_authenticated/bookmarks/'
      path: '/'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof AuthenticatedBookmarksIndexRouteImport
      parentRoute: typeof AuthenticatedBookmarksRoute
    }
    '/_authenticated/cost/$countryId': {
      id: '/_authenticated/cost/$countryId'
      path: '/$countryId'
      fullPath: '/cost/$countryId'
      preLoaderRoute: typeof AuthenticatedCostCountryIdRouteImport
      parentRoute: typeof AuthenticatedCostRoute
    }
    '/_authenticated/bookmarks/$id': {
      id: '/_authenticated/bookmarks/$id'
      path: '/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof AuthenticatedBookmarksIdRouteImport
      parentRoute: typeof AuthenticatedBookmarksRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthV1Route: typeof AuthV1Route
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthV1Route: AuthV1Route,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedBookmarksRouteChildren {
  AuthenticatedBookmarksIdRoute: typeof AuthenticatedBookmarksIdRoute
  AuthenticatedBookmarksIndexRoute: typeof AuthenticatedBookmarksIndexRoute
}

const AuthenticatedBookmarksRouteChildren: AuthenticatedBookmarksRouteChildren =
  {
    AuthenticatedBookmarksIdRoute: AuthenticatedBookmarksIdRoute,
    AuthenticatedBookmarksIndexRoute: AuthenticatedBookmarksIndexRoute,
  }

const AuthenticatedBookmarksRouteWithChildren =
  AuthenticatedBookmarksRoute._addFileChildren(
    AuthenticatedBookmarksRouteChildren,
  )

interface AuthenticatedCostRouteChildren {
  AuthenticatedCostCountryIdRoute: typeof AuthenticatedCostCountryIdRoute
  AuthenticatedCostIndexRoute: typeof AuthenticatedCostIndexRoute
}

const AuthenticatedCostRouteChildren: AuthenticatedCostRouteChildren = {
  AuthenticatedCostCountryIdRoute: AuthenticatedCostCountryIdRoute,
  AuthenticatedCostIndexRoute: AuthenticatedCostIndexRoute,
}

const AuthenticatedCostRouteWithChildren =
  AuthenticatedCostRoute._addFileChildren(AuthenticatedCostRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRouteWithChildren
  AuthenticatedCostRoute: typeof AuthenticatedCostRouteWithChildren
  AuthenticatedMainRoute: typeof AuthenticatedMainRoute
  AuthenticatedMypageRoute: typeof AuthenticatedMypageRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRouteWithChildren,
  AuthenticatedCostRoute: AuthenticatedCostRouteWithChildren,
  AuthenticatedMainRoute: AuthenticatedMainRoute,
  AuthenticatedMypageRoute: AuthenticatedMypageRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PreferenceRoute: PreferenceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
